<a href="https://colab.research.google.com/github/zainnabtarrek/SQL-Python-Data-Analysis-/blob/main/social_media_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.25.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.0.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.0.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26771 sha256=89400ecc805dce8dbaa9a290dd37e8059fa157d480beef1cb12b8c50b52c22d7
  Stored in directory: /root/.cache/pip/wheels/e9/bc/3a/8434bdcccf5779e72894a9b24fecbdcaf97940607eaf4bcdf9
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pandasql as ps
import sklearn

In [3]:
url="https://raw.githubusercontent.com/intern2grow/social-media-data-analysis/main/social_media_data.csv"
data=pd.read_csv(url)
data.head()

         date   platform post_type   likes  shares  comments   views
0  2023-05-24    Twitter     image   868.0   238.0     352.0  8836.0
1  2023-02-23    Twitter     image   944.0   610.0     146.0  5554.0
2  2023-03-18  Instagram     image  1067.0   858.0     365.0  4018.0
3  2023-06-12    Twitter      text   780.0   427.0     100.0  6999.0
4  2023-02-03  Instagram      text   836.0   893.0     443.0  5802.0

What was the total number of likes, shares, comments, and views (for videos) over the year?

In [4]:
query="""
SELECT
     post_type,SUM(likes + shares + comments + views) AS total_posts
FROM
    data
where
    post_type = 'video'

"""
totalrevenue=ps.sqldf(query, locals())
print(totalrevenue)

  post_type  total_posts
0     video    5705013.0

Which platform had the highest engagement? (engagement = likes + shares + comments)

In [5]:
query="""
SELECT
    platform,
    SUM(likes + shares + comments) AS engagement
FROM
    data
GROUP BY
    platform
ORDER BY
    engagement DESC
LIMIT 1;


"""
totalrevenue=ps.sqldf(query, locals())
print(totalrevenue)

    platform  engagement
0  Instagram   1405244.0

What was the average number of likes, shares, comments, and views per post on each platform?

In [8]:
query="""
SELECT
    platform,
   avg(likes),avg(likes),avg(shares),avg(comments),avg(views)
FROM
    data
GROUP BY
    platform
"""
totalrevenue=ps.sqldf(query, locals())
print(totalrevenue)

              platform   avg(likes)   avg(likes)  avg(shares)  avg(comments)  \
0             Facebook  1289.982428  1289.982428   513.141494     311.160317
1            Instagram  1305.837278  1305.837278   497.372404     301.046062
2  NonExistingPlatform  1150.166667  1150.166667   515.833333     285.500000
3              Twitter  1274.994152  1274.994152   482.437775     305.857980

    avg(views)
0  6984.239234
1  6905.875556
2  6729.166667
3  7013.258065

What was the total number of each type of post (video, image, text) on each platform?

In [9]:
data.head()

         date   platform post_type   likes  shares  comments   views
0  2023-05-24    Twitter     image   868.0   238.0     352.0  8836.0
1  2023-02-23    Twitter     image   944.0   610.0     146.0  5554.0
2  2023-03-18  Instagram     image  1067.0   858.0     365.0  4018.0
3  2023-06-12    Twitter      text   780.0   427.0     100.0  6999.0
4  2023-02-03  Instagram      text   836.0   893.0     443.0  5802.0

In [24]:
query = """
SELECT
    platform,
    post_type,
    COUNT(post_type) AS total
FROM
    data
WHERE
    platform != 'NonExistingPlatform'
GROUP BY
    platform,
    post_type
"""

totalrevenue = ps.sqldf(query, locals())
print(totalrevenue)

    platform post_type  total
0   Facebook     image    218
1   Facebook      text    204
2   Facebook     video    209
3  Instagram     image    267
4  Instagram      text    203
5  Instagram     video    208
6    Twitter     image    249
7    Twitter      text    219
8    Twitter     video    217

Which type of post had the highest average engagement?

In [28]:
query = """
SELECT
    post_type,
    AVG(likes + comments + shares) AS avg_engagement
FROM
    data
GROUP BY
    post_type
ORDER BY
    avg_engagement DESC
LIMIT 1;
"""

totalrevenue = ps.sqldf(query, locals())
print(totalrevenue)

  post_type  avg_engagement
0      text     2128.542071

What was the total engagement in each quarter of the year?

In [35]:
query="""
SELECT

  CASE
    WHEN strftime('%m', date) IN ('01', '02', '03') THEN 'Q1'
    WHEN strftime('%m', date) IN ('04', '05', '06') THEN 'Q2'
    WHEN strftime('%m', date) IN ('07', '08', '09') THEN 'Q3'
    WHEN strftime('%m', date) IN ('10', '11', '12') THEN 'Q4'
  END AS quarter,

    SUM(likes + shares + comments) AS total_engagement
FROM
    data
GROUP BY
    quarter
"""

totalrevenue = ps.sqldf(query, locals())
print(totalrevenue)

  quarter  total_engagement
0      Q1         1025381.0
1      Q2         1000644.0
2      Q3          978372.0
3      Q4         1131411.0